#!/usr/bin/env python
"""
Provides a quickstart to make your own setup
"""

from .dev_tools.cookiecutter_basics import initialize_git_repo, parse_args_setup

def make_init_py(name, version, comptype):
    template_setup = '''
"""
Some Documentation for %(name)s

----
"""
from setup import SetUp


class %(ClassName)s(SetUp):
    """
    Some description of a ``%(ClassName)s`` object
    """
    NAME = "%(name)s"
    VERSION = "%(version)s"
    TYPE = "%(comptype)s"

    def __init__(self, expid, parent_dir=".", components={}):
        """ 
        Documentation for SetUp %(name)s
        """
        super(%(ClassName)s, self).__init__(expid=expid, parent_dir=parent_dir, components=components)
''' % {"name": name, "version": version, "comptype": comptype, 
       "ClassName": "".join([name_part.capitalize() for name_part in name.split("_")])}
    with open(name+"/__init__.py", "w") as init_file:
        init_file.write(file_template)
