hostnames:
  login: ollie[01]
  compute: prod-[0-9]{3}
  mini: mini
nodetypes:
- login
- compute
- fat
- mini

batch_system: slurm
operating_system:
  linux: centos
compute_partition: mpp
post_partition: smp
cores:
  compute: 36

cpus:
  compute: 2

pool_directories:
  pool: /work/ollie/pool
  projects: /work/ollie/projects
cores_per_node: 36
