model: echam
repository: https://gitlab.dkrz.de/modular_esm/echam6
type: atmosphere
include_submodels: []
description: |
  The ECHAM atmosphere model, major version 6
  (someone from Hamburg)
  paper citation
license_text: |
  Please make sure you have a licence to use echam.In case you are
  unsure, please contact redmine....
pool_dir: '@MACHINE_POOL_DIR@/ECHAM6'
executable: echam6
version: 6.304p1
versions:
  6.304p1:
    repo_tag: 6.304p1
    dataset: r0007

INI_PARENT_DATE: 22941231
INI_PARENT_EXP_ID: khw0030
INPUT_DIR: '@POOL_DIR@/ECHAM6/input/@DATASET@'
INI_RESTART_DIR: '@POOL_DIR@/MPIESM/restart/dev/@INI_PARENT_EXP_ID@/restart/echam6'
namelist_changes:
  namelist.echam:
    runctl:
      out_expname: '@EXPID@'
      dt_start: '@START_DATE@'
      dt_stop: '@END_DATE@'
      dt_resume: '@START_DATE@'

    radctl:
      co2vmr: 888999
      ch4vmr: -99.2

resolutions:
  T63:
    res: T63
    levels: L47
    Timestep: 450
    _nx: 192
    _ny: 96
    cores_per_nodes:
      24:
        nproca: 24
        nprocb: 18
      36:
        nproca: 24
        nprocb: 18
  T31:
    res: T31               #SRC @RES@
    levels: L19
    Timestep: 450
    _nx: 96
    _ny: 48
  T127:
    res: T127
    levels: L47
    Timestep: 200
    _nx: 384
    _ny: 192

restart:
  frequency: 1
  unit: months

scenarios:
  always:
    inputs:
      cldoptprops: cldoptprops
      janspec: janspec
      jansurf: jansurf
      rrtmglw: rrtmglw
      rrtmgsw: rrtmgsw
      tslclim: tslclim
      vgrtclim: vgratclim
      vltclim: vltclim

  PI-CTRL:
    forcings:
      sst: pisst
      sic: pisic
      aerocoarse: piaerocoarse
      aerofin: piaerofin
      aerofarir: piaerofarir
      ozone: piozone

ADJ_INPUT_DIR: '@INPUT_DIR@/@RES@'
couplings:
  fesom:
    ADJ_INPUT_DIR: '@MESH_DIR@/tarfiles@RES@/input/echam6'
    remove_forcings:
    - sst
    - sic

inputs_in_workdir:
  cldoptprops: /ECHAM6_CldOptProps.nc
  janspec: unit.23
  jansurf: unit.24
  rrtmglw: rrtmg_lw.nc
  rrtmgsw: rrtmg_sw.nc
  tslclim: unit.92
  vgratclim: unit.91
  vltclim: unit.90
forcings_in_workdir:
  sic: unit.96
  sst: unit.20
  aerocoarse: aero_coarse_@YEAR@.nc
  aerofin: aero_fine_@YEAR@.nc
  aerofarir: aero_farir_@YEAR@.nc
  ozone: ozon@YEAR@
further_reading: []
datasets:
  r0007:
    amipsic:
      /@RES@/amip/@RES@_amipsic_@YEAR@.nc:
        from: 1870
        to: 2016
    amipsst:
      /@RES@/amip/@RES@_amipsst_@YEAR@.nc:
        from: 1870
        to: 2016
    histaerocoarse: /@RES@/aero2/@RES@_aeropt_kinne_sw_b14_coa.nc
    histaerofarir: /@RES@/aero2/@RES@_aeropt_kinne_lw_b16_coa.nc
    histaerofin:
      /@RES@/aero2/@RES@_aeropt_kinne_sw_b14_fin_1865.nc:
        to: 1864
      /@RES@/aero2/@RES@_aeropt_kinne_sw_b14_fin_@YEAR@.nc:
        from: 1865
        to: 2000
    histgreenh: /greenhouse_historical.nc
    histozone:
      /@RES@/ozone/@RES@_ozone_historical_1850.nc:
        to: 1850
      /@RES@_ozone_historical_@YEAR@.nc:
        from: 1851
        to: 2008
    histswflux:
      /solar_irradiance/swflux_14band_1850.nc:
        to: 1850
      /solar_irradiance/swflux_14band_@YEAR@.nc:
        from: 1851
    histvolcir:
      /@RES@/volcano_aerosols/strat_aerosol_ir_@RES@_1850.nc:
        to: 1850
      /@RES@/volcano_aerosols/strat_aerosol_ir_@RES@_@YEAR@.nc:
        from: 1851
        to: 1999
      /@RES@/volcano_aerosols/strat_aerosol_ir_@RES@_1999.nc:
        from: 2000
    histvolcsw:
      /@RES@/volcano_aerosols/strat_aerosol_sw_@RES@_1850.nc:
        to: 1850
      /@RES@/volcano_aerosols/strat_aerosol_sw_@RES@_@YEAR@.nc:
        from: 1851
        to: 1999
      /@RES@/volcano_aerosols/strat_aerosol_sw_@RES@_1999.nc:
        from: 2000
    piaerocoarse: /@RES@/aero/@RES@_aeropt_kinne_sw_b14_coa.nc
    piaerofarir: /@RES@/aero/@RES@_aeropt_kinne_lw_b16_coa.nc
    piaerofin: /@RES@/aero/@RES@_aeropt_kinne_sw_b14_fin_1865.nc
    piozone: /@RES@/@RES@_ozone_picontrol.nc
    pisic: /@RES@/@RES@@OCERES@_piControl-LR_sic_1880-2379.nc
    pisst: /@RES@/@RES@@OCERES@_piControl-LR_sst_1880-2379.nc
    cldoptprops: /ECHAM6_CldOptProps.nc
    janspec: /@RES@/@RES@@LEVELS@_jan_spec.nc
    jansurf: /@RES@/@RES@@OCERES@_jan_surf.nc
    rrtmglw: /rrtmg_lw.nc
    rrtmgsw: /rrtmg_sw.nc
    tslclim: /@RES@/@RES@_TSLCLIM.nc
    vgratclim: /@RES@/@RES@@OCERES@_VGRATCLIM.nc
    vltclim: /@RES@/@RES@@OCERES@_VLTCLIM.nc
